AWSTemplateFormatVersion: 2010-09-09


Description: >
  Creates the AWS infrastructure resources for running an angular app

Parameters:

  BaseUrl:
    Type: String
    Default: liandrasoftworks.com
    Description : The DNS name of an existing Amazon Route 53 hosted zone,
    AllowedPattern : (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)[^\\.]$
    ConstraintDescription : Must be a valid DNS zone name WITHOUT trailing period.

  AppUrl:
    Type: String
    Default: aws-angular-starter.liandrasoftworks.com
    Description: The subdomain you want to use for your app. This example creates a subdomain and an A record

  AcmCertArn:
    Type: String
    Description: ARN of the Amazon Certificate Manager cert to use for SSL

Resources:

  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-app
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  AppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: WebAppBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref AppBucket
                - /*
      Bucket: !Ref AppBucket

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access identity between CloudFront and S3 bucket

  AppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig: 
        Origins:
        - DomainName: !Sub ${AppBucket}.s3.amazonaws.com
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
        Enabled: 'true'
        Comment: CloudFront distribution for Angular App
        CustomErrorResponses:
        - ErrorCachingMinTTL: 5
          ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
        DefaultRootObject: index.html
        Aliases:
        - !Ref AppUrl
        - !Ref BaseUrl
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: 'true'
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertArn
          SslSupportMethod: sni-only

  WebAppDns:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${BaseUrl}.
      Comment: IP4 & IP6 alias targeted to CloudFront Distribution.
      RecordSets:
      - Name: !Ref AppUrl
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt 
            - AppDistribution
            - DomainName
      - Name: !Ref AppUrl
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt 
            - AppDistribution
            - DomainName
#Uncomment this section if you want your base URL to open your app also
      # - Name: !Ref BaseUrl
      #   Type: A
      #   AliasTarget:
      #     HostedZoneId: Z2FDTNDATAQYW2
      #     DNSName: !GetAtt 
      #       - AppDistribution
      #       - DomainName
      # - Name: !Ref BaseUrl
      #   Type: AAAA
      #   AliasTarget:
      #     HostedZoneId: Z2FDTNDATAQYW2
      #     DNSName: !GetAtt 
      #       - AppDistribution
      #       - DomainName
            
Outputs:
  AppBucket:
    Description: Where the app was deployed to
    Value: !Ref AppBucket
  WebsiteURL:
    Value: !GetAtt 
      - AppBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  CloudFrontURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - AppDistribution
          - DomainName
    Description: URL for website CDN